package com.batodev.sudoku.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

private const val GREEN_LIGHT_PRIMARY = 0xFF1F6D19L
private const val GREEN_LIGHT_ON_PRIMARY = 0xFFFFFFFFL
private const val GREEN_LIGHT_PRIMARY_CONTAINER = 0xFFA4F791L
private const val GREEN_LIGHT_ON_PRIMARY_CONTAINER = 0xFF002200L
private const val GREEN_LIGHT_SECONDARY = 0xFF54634EL
private const val GREEN_LIGHT_ON_SECONDARY = 0xFFFFFFFFL
private const val GREEN_LIGHT_SECONDARY_CONTAINER = 0xFFD7E8CDL
private const val GREEN_LIGHT_ON_SECONDARY_CONTAINER = 0xFF121F0EL
private const val GREEN_LIGHT_TERTIARY = 0xFF386569L
private const val GREEN_LIGHT_ON_TERTIARY = 0xFFFFFFFFL
private const val GREEN_LIGHT_TERTIARY_CONTAINER = 0xFFBCEBEEL
private const val GREEN_LIGHT_ON_TERTIARY_CONTAINER = 0xFF002022L
private const val GREEN_LIGHT_ERROR = 0xFFBA1A1AL
private const val GREEN_LIGHT_ERROR_CONTAINER = 0xFFFFDAD6L
private const val GREEN_LIGHT_ON_ERROR = 0xFFFFFFFFL
private const val GREEN_LIGHT_ON_ERROR_CONTAINER = 0xFF410002L
private const val GREEN_LIGHT_BACKGROUND = 0xFFFCFDF6L
private const val GREEN_LIGHT_ON_BACKGROUND = 0xFF1A1C18L
private const val GREEN_LIGHT_SURFACE = 0xFFFCFDF6L
private const val GREEN_LIGHT_ON_SURFACE = 0xFF1A1C18L
private const val GREEN_LIGHT_SURFACE_VARIANT = 0xFFDFE4D8L
private const val GREEN_LIGHT_ON_SURFACE_VARIANT = 0xFF43483FL
private const val GREEN_LIGHT_OUTLINE = 0xFF73796EL
private const val GREEN_LIGHT_INVERSE_ON_SURFACE = 0xFFF1F1EBL
private const val GREEN_LIGHT_INVERSE_SURFACE = 0xFF2F312DL
private const val GREEN_LIGHT_INVERSE_PRIMARY = 0xFF89DA78L
private const val GREEN_LIGHT_SURFACE_TINT = 0xFF1D461AL
private const val GREEN_DARK_PRIMARY = 0xFF89DA78L
private const val GREEN_DARK_ON_PRIMARY = 0xFF003A01L
private const val GREEN_DARK_PRIMARY_CONTAINER = 0xFF005302L
private const val GREEN_DARK_ON_PRIMARY_CONTAINER = 0xFFA4F791L
private const val GREEN_DARK_SECONDARY = 0xFFBBCBB2L
private const val GREEN_DARK_ON_SECONDARY = 0xFF263422L
private const val GREEN_DARK_SECONDARY_CONTAINER = 0xFF3C4B37L
private const val GREEN_DARK_ON_SECONDARY_CONTAINER = 0xFFD7E8CDL
private const val GREEN_DARK_TERTIARY = 0xFFA0CFD2L
private const val GREEN_DARK_ON_TERTIARY = 0xFF00373AL
private const val GREEN_DARK_TERTIARY_CONTAINER = 0xFF1E4D51L
private const val GREEN_DARK_ON_TERTIARY_CONTAINER = 0xFFBCEBEEL
private const val GREEN_DARK_ERROR = 0xFFFFB4ABL
private const val GREEN_DARK_ERROR_CONTAINER = 0xFF93000AL
private const val GREEN_DARK_ON_ERROR = 0xFF690005L
private const val GREEN_DARK_ON_ERROR_CONTAINER = 0xFFFFDAD6L
private const val GREEN_DARK_BACKGROUND = 0xFF1A1C18L
private const val GREEN_DARK_ON_BACKGROUND = 0xFFE2E3DDL
private const val GREEN_DARK_SURFACE = 0xFF1A1C18L
private const val GREEN_DARK_ON_SURFACE = 0xFFE2E3DDL
private const val GREEN_DARK_SURFACE_VARIANT = 0xFF43483FL
private const val GREEN_DARK_ON_SURFACE_VARIANT = 0xFFC3C8BCL
private const val GREEN_DARK_OUTLINE = 0xFF8D9387L
private const val GREEN_DARK_INVERSE_ON_SURFACE = 0xFF1A1C18L
private const val GREEN_DARK_INVERSE_SURFACE = 0xFFE2E3DDL
private const val GREEN_DARK_INVERSE_PRIMARY = 0xFF1F6D19L
private const val GREEN_DARK_SURFACE_TINT = 0xFF55944FL
private const val PINK_LIGHT_PRIMARY = 0xFF9C4144L
private const val PINK_LIGHT_ON_PRIMARY = 0xFFFFFFFFL
private const val PINK_LIGHT_PRIMARY_CONTAINER = 0xFFFFDAD9L
private const val PINK_LIGHT_ON_PRIMARY_CONTAINER = 0xFF410008L
private const val PINK_LIGHT_SECONDARY = 0xFF775656L
private const val PINK_LIGHT_ON_SECONDARY = 0xFFFFFFFFL
private const val PINK_LIGHT_SECONDARY_CONTAINER = 0xFFFFDAD9L
private const val PINK_LIGHT_ON_SECONDARY_CONTAINER = 0xFF2C1515L
private const val PINK_LIGHT_TERTIARY = 0xFF755A2FL
private const val PINK_LIGHT_ON_TERTIARY = 0xFFFFFFFFL
private const val PINK_LIGHT_TERTIARY_CONTAINER = 0xFFFFDEADL
private const val PINK_LIGHT_ON_TERTIARY_CONTAINER = 0xFF281900L
private const val PINK_LIGHT_ERROR = 0xFFBA1A1AL
private const val PINK_LIGHT_ERROR_CONTAINER = 0xFFFFDAD6L
private const val PINK_LIGHT_ON_ERROR = 0xFFFFFFFFL
private const val PINK_LIGHT_ON_ERROR_CONTAINER = 0xFF410002L
private const val PINK_LIGHT_BACKGROUND = 0xFFFFFBFFL
private const val PINK_LIGHT_ON_BACKGROUND = 0xFF201A1AL
private const val PINK_LIGHT_SURFACE = 0xFFFFFBFFL
private const val PINK_LIGHT_ON_SURFACE = 0xFF201A1AL
private const val PINK_LIGHT_SURFACE_VARIANT = 0xFFF4DDDCL
private const val PINK_LIGHT_ON_SURFACE_VARIANT = 0xFF524343L
private const val PINK_LIGHT_OUTLINE = 0xFF857372L
private const val PINK_LIGHT_INVERSE_ON_SURFACE = 0xFFFBEEEDL
private const val PINK_LIGHT_INVERSE_SURFACE = 0xFF362F2EL
private const val PINK_LIGHT_INVERSE_PRIMARY = 0xFFFFB3B2L
private const val PINK_LIGHT_SURFACE_TINT = 0xFF351617L
private const val PINK_DARK_PRIMARY = 0xFFD89896L
private const val PINK_DARK_ON_PRIMARY = 0xFF5F131AL
private const val PINK_DARK_PRIMARY_CONTAINER = 0xFF7E2A2EL
private const val PINK_DARK_ON_PRIMARY_CONTAINER = 0xFFFFDAD9L
private const val PINK_DARK_SECONDARY = 0xFFE6BDBCL
private const val PINK_DARK_ON_SECONDARY = 0xFF442929L
private const val PINK_DARK_SECONDARY_CONTAINER = 0xFF5D3F3FL
private const val PINK_DARK_ON_SECONDARY_CONTAINER = 0xFFFFDAD9L
private const val PINK_DARK_TERTIARY = 0xFFE4C18DL
private const val PINK_DARK_ON_TERTIARY = 0xFF422C05L
private const val PINK_DARK_TERTIARY_CONTAINER = 0xFF5B431AL
private const val PINK_DARK_ON_TERTIARY_CONTAINER = 0xFFFFDEADL
private const val PINK_DARK_ERROR = 0xFFFFB4ABL
private const val PINK_DARK_ERROR_CONTAINER = 0xFF93000AL
private const val PINK_DARK_ON_ERROR = 0xFF690005L
private const val PINK_DARK_ON_ERROR_CONTAINER = 0xFFFFDAD6L
private const val PINK_DARK_BACKGROUND = 0xFF201A1AL
private const val PINK_DARK_ON_BACKGROUND = 0xFFECE0DFL
private const val PINK_DARK_SURFACE = 0xFF201A1AL
private const val PINK_DARK_ON_SURFACE = 0xFFECE0DFL
private const val PINK_DARK_SURFACE_VARIANT = 0xFF524343L
private const val PINK_DARK_ON_SURFACE_VARIANT = 0xFFD7C1C1L
private const val PINK_DARK_OUTLINE = 0xFFA08C8CL
private const val PINK_DARK_INVERSE_ON_SURFACE = 0xFF201A1AL
private const val PINK_DARK_INVERSE_SURFACE = 0xFFECE0DFL
private const val PINK_DARK_INVERSE_PRIMARY = 0xFF9C4144L
private const val PINK_DARK_SURFACE_TINT = 0xFF463030L
private const val YELLOW_LIGHT_PRIMARY = 0xFF5A6400L
private const val YELLOW_LIGHT_ON_PRIMARY = 0xFFFFFFFFL
private const val YELLOW_LIGHT_PRIMARY_CONTAINER = 0xFFDDEB77L
private const val YELLOW_LIGHT_ON_PRIMARY_CONTAINER = 0xFF1A1E00L
private const val YELLOW_LIGHT_SECONDARY = 0xFF5E6144L
private const val YELLOW_LIGHT_ON_SECONDARY = 0xFFFFFFFFL
private const val YELLOW_LIGHT_SECONDARY_CONTAINER = 0xFFBEC097L
private const val YELLOW_LIGHT_ON_SECONDARY_CONTAINER = 0xFF1B1D07L
private const val YELLOW_LIGHT_TERTIARY = 0xFF3B665BL
private const val YELLOW_LIGHT_ON_TERTIARY = 0xFFFFFFFFL
private const val YELLOW_LIGHT_TERTIARY_CONTAINER = 0xFFBEECDDL
private const val YELLOW_LIGHT_ON_TERTIARY_CONTAINER = 0xFF002019L
private const val YELLOW_LIGHT_ERROR = 0xFFBA1A1AL
private const val YELLOW_LIGHT_ERROR_CONTAINER = 0xFFFFDAD6L
private const val YELLOW_LIGHT_ON_ERROR = 0xFFFFFFFFL
private const val YELLOW_LIGHT_ON_ERROR_CONTAINER = 0xFF410002L
private const val YELLOW_LIGHT_BACKGROUND = 0xFFF6F7EDL
private const val YELLOW_LIGHT_ON_BACKGROUND = 0xFF1C1C17L
private const val YELLOW_LIGHT_SURFACE = 0xFFF6F7EDL
private const val YELLOW_LIGHT_ON_SURFACE = 0xFF1C1C17L
private const val YELLOW_LIGHT_SURFACE_VARIANT = 0xFFE4E3D2L
private const val YELLOW_LIGHT_ON_SURFACE_VARIANT = 0xFF47483BL
private const val YELLOW_LIGHT_OUTLINE = 0xFF78786AL
private const val YELLOW_LIGHT_INVERSE_ON_SURFACE = 0xFFF3F1E8L
private const val YELLOW_LIGHT_INVERSE_SURFACE = 0xFF31312BL
private const val YELLOW_LIGHT_INVERSE_PRIMARY = 0xFFC1CF5FL
private const val YELLOW_LIGHT_SURFACE_TINT = 0xFF5A6400L
private const val YELLOW_DARK_PRIMARY = 0xFFD1CA53L
private const val YELLOW_DARK_ON_PRIMARY = 0xFF343200L
private const val YELLOW_DARK_PRIMARY_CONTAINER = 0xFF4C4900L
private const val YELLOW_DARK_ON_PRIMARY_CONTAINER = 0xFFEEE76CL
private const val YELLOW_DARK_SECONDARY = 0xFFCCC8A4L
private const val YELLOW_DARK_ON_SECONDARY = 0xFF333118L
private const val YELLOW_DARK_SECONDARY_CONTAINER = 0xFF4A482CL
private const val YELLOW_DARK_ON_SECONDARY_CONTAINER = 0xFFE8E4BEL
private const val YELLOW_DARK_TERTIARY = 0xFFA5D0BAL
private const val YELLOW_DARK_ON_TERTIARY = 0xFF0D3728L
private const val YELLOW_DARK_TERTIARY_CONTAINER = 0xFF274E3EL
private const val YELLOW_DARK_ON_TERTIARY_CONTAINER = 0xFFC1ECD6L
private const val YELLOW_DARK_ERROR = 0xFFFFB4ABL
private const val YELLOW_DARK_ERROR_CONTAINER = 0xFF93000AL
private const val YELLOW_DARK_ON_ERROR = 0xFF690005L
private const val YELLOW_DARK_ON_ERROR_CONTAINER = 0xFFFFDAD6L
private const val YELLOW_DARK_BACKGROUND = 0xFF1C1C16L
private const val YELLOW_DARK_ON_BACKGROUND = 0xFFE6E2D9L
private const val YELLOW_DARK_SURFACE = 0xFF1C1C16L
private const val YELLOW_DARK_ON_SURFACE = 0xFFE6E2D9L
private const val YELLOW_DARK_SURFACE_VARIANT = 0xFF49473AL
private const val YELLOW_DARK_ON_SURFACE_VARIANT = 0xFFCAC7B5L
private const val YELLOW_DARK_OUTLINE = 0xFF949181L
private const val YELLOW_DARK_INVERSE_ON_SURFACE = 0xFF1C1C16L
private const val YELLOW_DARK_INVERSE_SURFACE = 0xFFE6E2D9L
private const val YELLOW_DARK_INVERSE_PRIMARY = 0xFF656100L
private const val YELLOW_DARK_SURFACE_TINT = 0xFF3F3D19L
private const val LAVENDER_LIGHT_PRIMARY = 0xFF7F4894L
private const val LAVENDER_LIGHT_ON_PRIMARY = 0xFFFFFFFFL
private const val LAVENDER_LIGHT_PRIMARY_CONTAINER = 0xFFF8D8FFL
private const val LAVENDER_LIGHT_ON_PRIMARY_CONTAINER = 0xFF320046L
private const val LAVENDER_LIGHT_SECONDARY = 0xFF69596DL
private const val LAVENDER_LIGHT_ON_SECONDARY = 0xFFFFFFFFL
private const val LAVENDER_LIGHT_SECONDARY_CONTAINER = 0xFFF1DCF3L
private const val LAVENDER_LIGHT_ON_SECONDARY_CONTAINER = 0xFF231728L
private const val LAVENDER_LIGHT_TERTIARY = 0xFF81524FL
private const val LAVENDER_LIGHT_ON_TERTIARY = 0xFFFFFFFFL
private const val LAVENDER_LIGHT_TERTIARY_CONTAINER = 0xFFFFDAD8L
private const val LAVENDER_LIGHT_ON_TERTIARY_CONTAINER = 0xFF331110L
private const val LAVENDER_LIGHT_ERROR = 0xFFBA1A1AL
private const val LAVENDER_LIGHT_ERROR_CONTAINER = 0xFFFFDAD6L
private const val LAVENDER_LIGHT_ON_ERROR = 0xFFFFFFFFL
private const val LAVENDER_LIGHT_ON_ERROR_CONTAINER = 0xFF410002L
private const val LAVENDER_LIGHT_BACKGROUND = 0xFFFFFBFFL
private const val LAVENDER_LIGHT_ON_BACKGROUND = 0xFF1E1B1EL
private const val LAVENDER_LIGHT_SURFACE = 0xFFFFFBFFL
private const val LAVENDER_LIGHT_ON_SURFACE = 0xFF1E1B1EL
private const val LAVENDER_LIGHT_SURFACE_VARIANT = 0xFFEBDFE9L
private const val LAVENDER_LIGHT_ON_SURFACE_VARIANT = 0xFF4C444DL
private const val LAVENDER_LIGHT_OUTLINE = 0xFF7D747DL
private const val LAVENDER_LIGHT_INVERSE_ON_SURFACE = 0xFFF7EFF3L
private const val LAVENDER_LIGHT_INVERSE_SURFACE = 0xFF332F33L
private const val LAVENDER_LIGHT_INVERSE_PRIMARY = 0xFFECB1FFL
private const val LAVENDER_LIGHT_SURFACE_TINT = 0xFF321D3AL
private const val LAVENDER_DARK_PRIMARY = 0xFFECB1FFL
private const val LAVENDER_DARK_ON_PRIMARY = 0xFF4C1662L
private const val LAVENDER_DARK_PRIMARY_CONTAINER = 0xFF65307AL
private const val LAVENDER_DARK_ON_PRIMARY_CONTAINER = 0xFFF8D8FFL
private const val LAVENDER_DARK_SECONDARY = 0xFFD5C0D7L
private const val LAVENDER_DARK_ON_SECONDARY = 0xFF392C3DL
private const val LAVENDER_DARK_SECONDARY_CONTAINER = 0xFF514254L
private const val LAVENDER_DARK_ON_SECONDARY_CONTAINER = 0xFFF1DCF3L
private const val LAVENDER_DARK_TERTIARY = 0xFFF5B7B4L
private const val LAVENDER_DARK_ON_TERTIARY = 0xFF4C2524L
private const val LAVENDER_DARK_TERTIARY_CONTAINER = 0xFF663B39L
private const val LAVENDER_DARK_ON_TERTIARY_CONTAINER = 0xFFFFDAD8L
private const val LAVENDER_DARK_ERROR = 0xFFFFB4ABL
private const val LAVENDER_DARK_ERROR_CONTAINER = 0xFF93000AL
private const val LAVENDER_DARK_ON_ERROR = 0xFF690005L
private const val LAVENDER_DARK_ON_ERROR_CONTAINER = 0xFFFFDAD6L
private const val LAVENDER_DARK_BACKGROUND = 0xFF1E1B1EL
private const val LAVENDER_DARK_ON_BACKGROUND = 0xFFE8E0E5L
private const val LAVENDER_DARK_SURFACE = 0xFF1E1B1EL
private const val LAVENDER_DARK_ON_SURFACE = 0xFFE8E0E5L
private const val LAVENDER_DARK_SURFACE_VARIANT = 0xFF4C444DL
private const val LAVENDER_DARK_ON_SURFACE_VARIANT = 0xFFCEC3CDL
private const val LAVENDER_DARK_OUTLINE = 0xFF988E97L
private const val LAVENDER_DARK_INVERSE_ON_SURFACE = 0xFF1E1B1EL
private const val LAVENDER_DARK_INVERSE_SURFACE = 0xFFE8E0E5L
private const val LAVENDER_DARK_INVERSE_PRIMARY = 0xFF7F4894L
private const val LAVENDER_DARK_SURFACE_TINT = 0xFF47354DL
private const val BLACK_AND_WHITE_LIGHT_PRIMARY = 0xFF000000L
private const val BLACK_AND_WHITE_LIGHT_ON_PRIMARY = 0xFFFFFFFFL
private const val BLACK_AND_WHITE_LIGHT_PRIMARY_CONTAINER = 0xFFD8D8D8L
private const val BLACK_AND_WHITE_LIGHT_ON_PRIMARY_CONTAINER = 0xFF0C0C0CL
private const val BLACK_AND_WHITE_LIGHT_SECONDARY = 0xFF000000L
private const val BLACK_AND_WHITE_LIGHT_ON_SECONDARY = 0xFFE0E0E0L
private const val BLACK_AND_WHITE_LIGHT_SECONDARY_CONTAINER = 0xFFCCCCCCL
private const val BLACK_AND_WHITE_LIGHT_ON_SECONDARY_CONTAINER = 0xFF202020L
private const val BLACK_AND_WHITE_LIGHT_TERTIARY = 0xFFFFFFFFL
private const val BLACK_AND_WHITE_LIGHT_ON_TERTIARY = 0xFF2E2E2EL
private const val BLACK_AND_WHITE_LIGHT_TERTIARY_CONTAINER = 0xFF047291L
private const val BLACK_AND_WHITE_LIGHT_ON_TERTIARY_CONTAINER = 0xFF331110L
private const val BLACK_AND_WHITE_LIGHT_ERROR = 0xFFBA1A1AL
private const val BLACK_AND_WHITE_LIGHT_ERROR_CONTAINER = 0xFFFFDAD6L
private const val BLACK_AND_WHITE_LIGHT_ON_ERROR = 0xFFFFFFFFL
private const val BLACK_AND_WHITE_LIGHT_ON_ERROR_CONTAINER = 0xFF410002L
private const val BLACK_AND_WHITE_LIGHT_BACKGROUND = 0xFFFFFFFFL
private const val BLACK_AND_WHITE_LIGHT_ON_BACKGROUND = 0xFF1A1A1AL
private const val BLACK_AND_WHITE_LIGHT_SURFACE = 0xFFFFFFFFL
private const val BLACK_AND_WHITE_LIGHT_ON_SURFACE = 0xFF1E1B1EL
private const val BLACK_AND_WHITE_LIGHT_SURFACE_VARIANT = 0xFFE9E9E9L
private const val BLACK_AND_WHITE_LIGHT_ON_SURFACE_VARIANT = 0xFF4D4D4DL
private const val BLACK_AND_WHITE_LIGHT_OUTLINE = 0xFF7D747DL
private const val BLACK_AND_WHITE_LIGHT_INVERSE_ON_SURFACE = 0xFFF1F1F1L
private const val BLACK_AND_WHITE_LIGHT_INVERSE_SURFACE = 0xFF313131L
private const val BLACK_AND_WHITE_LIGHT_INVERSE_PRIMARY = 0xFFEEEEEEL
private const val BLACK_AND_WHITE_LIGHT_SURFACE_TINT = 0xFF000000L
private const val BLACK_AND_WHITE_DARK_PRIMARY = 0xFFFFFFFFL
private const val BLACK_AND_WHITE_DARK_ON_PRIMARY = 0xFF313131L
private const val BLACK_AND_WHITE_DARK_PRIMARY_CONTAINER = 0xFF4D4D4DL
private const val BLACK_AND_WHITE_DARK_ON_PRIMARY_CONTAINER = 0xFFD1D1D1L
private const val BLACK_AND_WHITE_DARK_SECONDARY = 0xFFE6E6E6L
private const val BLACK_AND_WHITE_DARK_ON_SECONDARY = 0xFF161616L
private const val BLACK_AND_WHITE_DARK_SECONDARY_CONTAINER = 0xFF4D4D4DL
private const val BLACK_AND_WHITE_DARK_ON_SECONDARY_CONTAINER = 0xFFE4E4E4L
private const val BLACK_AND_WHITE_DARK_TERTIARY = 0xFF4A849EL
private const val BLACK_AND_WHITE_DARK_ON_TERTIARY = 0xFFDDDDDDL
private const val BLACK_AND_WHITE_DARK_TERTIARY_CONTAINER = 0xFF047291L
private const val BLACK_AND_WHITE_DARK_ON_TERTIARY_CONTAINER = 0xFF331110L
private const val BLACK_AND_WHITE_DARK_ERROR = 0xFFBA1A1AL
private const val BLACK_AND_WHITE_DARK_ERROR_CONTAINER = 0xFFFFDAD6L
private const val BLACK_AND_WHITE_DARK_ON_ERROR = 0xFFFFFFFFL
private const val BLACK_AND_WHITE_DARK_ON_ERROR_CONTAINER = 0xFF410002L
private const val BLACK_AND_WHITE_DARK_BACKGROUND = 0xFF181818L
private const val BLACK_AND_WHITE_DARK_ON_BACKGROUND = 0xFFF1F1F1L
private const val BLACK_AND_WHITE_DARK_SURFACE = 0xFF181818L
private const val BLACK_AND_WHITE_DARK_ON_SURFACE = 0xFFF1F1F1L
private const val BLACK_AND_WHITE_DARK_SURFACE_VARIANT = 0xFF3C3C3CL
private const val BLACK_AND_WHITE_DARK_ON_SURFACE_VARIANT = 0xFFCFCFCFL
private const val BLACK_AND_WHITE_DARK_OUTLINE = 0xFF7D747DL
private const val BLACK_AND_WHITE_DARK_INVERSE_ON_SURFACE = 0xFF252525L
private const val BLACK_AND_WHITE_DARK_INVERSE_SURFACE = 0xFFC0C0C0L
private const val BLACK_AND_WHITE_DARK_INVERSE_PRIMARY = 0xFFE0E0E0L
private const val BLACK_AND_WHITE_DARK_SURFACE_TINT = 0xFFFFFFFFL
private const val BLUE_LIGHT_PRIMARY = 0xFF085EB0L
private const val BLUE_LIGHT_ON_PRIMARY = 0xFFFFFFFFL
private const val BLUE_LIGHT_PRIMARY_CONTAINER = 0xFFD5E3FFL
private const val BLUE_LIGHT_ON_PRIMARY_CONTAINER = 0xFF001C3BL
private const val BLUE_LIGHT_SECONDARY = 0xFF555F71L
private const val BLUE_LIGHT_ON_SECONDARY = 0xFFFFFFFFL
private const val BLUE_LIGHT_SECONDARY_CONTAINER = 0xFFD9E3F8L
private const val BLUE_LIGHT_ON_SECONDARY_CONTAINER = 0xFF121C2BL
private const val BLUE_LIGHT_TERTIARY = 0xFF6E5676L
private const val BLUE_LIGHT_ON_TERTIARY = 0xFFFFFFFFL
private const val BLUE_LIGHT_TERTIARY_CONTAINER = 0xFFF8D8FEL
private const val BLUE_LIGHT_ON_TERTIARY_CONTAINER = 0xFF27132FL
private const val BLUE_LIGHT_ERROR = 0xFFBA1A1AL
private const val BLUE_LIGHT_ERROR_CONTAINER = 0xFFFFDAD6L
private const val BLUE_LIGHT_ON_ERROR = 0xFFFFFFFFL
private const val BLUE_LIGHT_ON_ERROR_CONTAINER = 0xFF410002L
private const val BLUE_LIGHT_BACKGROUND = 0xFFFDFBFFL
private const val BLUE_LIGHT_ON_BACKGROUND = 0xFF1A1C1EL
private const val BLUE_LIGHT_INVERSE_ON_SURFACE = 0xFFF1F0F4L
private const val BLUE_LIGHT_INVERSE_SURFACE = 0xFF2F3033L
private const val BLUE_LIGHT_INVERSE_PRIMARY = 0xFFA7C8FFL
private const val BLUE_LIGHT_SURFACE_TINT = 0xFF085EB0L
private const val BLUE_LIGHT_OUTLINE_VARIANT = 0xFFC4C6CFL
private const val BLUE_LIGHT_SCRIM = 0xFF000000L
private const val BLUE_LIGHT_SURFACE = 0xFFFDFBFFL
private const val BLUE_LIGHT_ON_SURFACE = 0xFF1A1C1EL
private const val BLUE_DARK_PRIMARY = 0xFFA7C8FFL
private const val BLUE_DARK_ON_PRIMARY = 0xFF003060L
private const val BLUE_DARK_PRIMARY_CONTAINER = 0xFF004787L
private const val BLUE_DARK_ON_PRIMARY_CONTAINER = 0xFFD5E3FFL
private const val BLUE_DARK_SECONDARY = 0xFFBDC7DCL
private const val BLUE_DARK_ON_SECONDARY = 0xFF273141L
private const val BLUE_DARK_SECONDARY_CONTAINER = 0xFF3D4758L
private const val BLUE_DARK_ON_SECONDARY_CONTAINER = 0xFFD9E3F8L
private const val BLUE_DARK_TERTIARY = 0xFFDBBDE2L
private const val BLUE_DARK_ON_TERTIARY = 0xFF3E2845L
private const val BLUE_DARK_TERTIARY_CONTAINER = 0xFF553F5DL
private const val BLUE_DARK_ON_TERTIARY_CONTAINER = 0xFFF8D8FEL
private const val BLUE_DARK_ERROR = 0xFFFFB4ABL
private const val BLUE_DARK_ERROR_CONTAINER = 0xFF93000AL
private const val BLUE_DARK_ON_ERROR = 0xFF690005L
private const val BLUE_DARK_ON_ERROR_CONTAINER = 0xFFFFDAD6L
private const val BLUE_DARK_BACKGROUND = 0xFF1A1C1EL
private const val BLUE_DARK_ON_BACKGROUND = 0xFFE3E2E6L
private const val BLUE_DARK_OUTLINE = 0xFF8D9199L
private const val BLUE_DARK_INVERSE_ON_SURFACE = 0xFF1A1C1EL
private const val BLUE_DARK_INVERSE_SURFACE = 0xFFE3E2E6L
private const val BLUE_DARK_INVERSE_PRIMARY = 0xFF085EB0L
private const val BLUE_DARK_SURFACE_TINT = 0xFFA7C8FFL
private const val BLUE_DARK_OUTLINE_VARIANT = 0xFF43474EL
private const val BLUE_DARK_SCRIM = 0xFF000000L
private const val BLUE_DARK_SURFACE = 0xFF1A1C1EL
private const val BLUE_DARK_ON_SURFACE = 0xFFC7C6CAL
private const val BLUE_DARK_SURFACE_VARIANT = 0xFF43474EL
private const val BLUE_DARK_ON_SURFACE_VARIANT = 0xFFC4C6CFL

class AppColorScheme {
    fun getTheme(appTheme: AppTheme, dark: Boolean = false): ColorScheme {
        return when (appTheme) {
            AppTheme.Green -> if (dark) greenDark else greenLight
            AppTheme.Blue -> if (dark) blueDark else blueLight
            AppTheme.Peach -> if (dark) pinkDark else pinkLight
            AppTheme.Yellow -> if (dark) yellowDark else yellowLight
            AppTheme.Lavender -> if (dark) lavenderDark else lavenderLight
            AppTheme.BlackAndWhite -> if (dark) blackAndWhiteDark else blackAndWhiteLight
        }
    }

    private val greenLight = lightColorScheme(
        primary = Color(GREEN_LIGHT_PRIMARY),
        onPrimary = Color(GREEN_LIGHT_ON_PRIMARY),
        primaryContainer = Color(GREEN_LIGHT_PRIMARY_CONTAINER),
        onPrimaryContainer = Color(GREEN_LIGHT_ON_PRIMARY_CONTAINER),
        secondary = Color(GREEN_LIGHT_SECONDARY),
        onSecondary = Color(GREEN_LIGHT_ON_SECONDARY),
        secondaryContainer = Color(GREEN_LIGHT_SECONDARY_CONTAINER),
        onSecondaryContainer = Color(GREEN_LIGHT_ON_SECONDARY_CONTAINER),
        tertiary = Color(GREEN_LIGHT_TERTIARY),
        onTertiary = Color(GREEN_LIGHT_ON_TERTIARY),
        tertiaryContainer = Color(GREEN_LIGHT_TERTIARY_CONTAINER),
        onTertiaryContainer = Color(GREEN_LIGHT_ON_TERTIARY_CONTAINER),
        error = Color(GREEN_LIGHT_ERROR),
        errorContainer = Color(GREEN_LIGHT_ERROR_CONTAINER),
        onError = Color(GREEN_LIGHT_ON_ERROR),
        onErrorContainer = Color(GREEN_LIGHT_ON_ERROR_CONTAINER),
        background = Color(GREEN_LIGHT_BACKGROUND),
        onBackground = Color(GREEN_LIGHT_ON_BACKGROUND),
        surface = Color(GREEN_LIGHT_SURFACE),
        onSurface = Color(GREEN_LIGHT_ON_SURFACE),
        surfaceVariant = Color(GREEN_LIGHT_SURFACE_VARIANT),
        onSurfaceVariant = Color(GREEN_LIGHT_ON_SURFACE_VARIANT),
        outline = Color(GREEN_LIGHT_OUTLINE),
        inverseOnSurface = Color(GREEN_LIGHT_INVERSE_ON_SURFACE),
        inverseSurface = Color(GREEN_LIGHT_INVERSE_SURFACE),
        inversePrimary = Color(GREEN_LIGHT_INVERSE_PRIMARY),
        surfaceTint = Color(GREEN_LIGHT_SURFACE_TINT),
    )

    private val greenDark = darkColorScheme(
        primary = Color(GREEN_DARK_PRIMARY),
        onPrimary = Color(GREEN_DARK_ON_PRIMARY),
        primaryContainer = Color(GREEN_DARK_PRIMARY_CONTAINER),
        onPrimaryContainer = Color(GREEN_DARK_ON_PRIMARY_CONTAINER),
        secondary = Color(GREEN_DARK_SECONDARY),
        onSecondary = Color(GREEN_DARK_ON_SECONDARY),
        secondaryContainer = Color(GREEN_DARK_SECONDARY_CONTAINER),
        onSecondaryContainer = Color(GREEN_DARK_ON_SECONDARY_CONTAINER),
        tertiary = Color(GREEN_DARK_TERTIARY),
        onTertiary = Color(GREEN_DARK_ON_TERTIARY),
        tertiaryContainer = Color(GREEN_DARK_TERTIARY_CONTAINER),
        onTertiaryContainer = Color(GREEN_DARK_ON_TERTIARY_CONTAINER),
        error = Color(GREEN_DARK_ERROR),
        errorContainer = Color(GREEN_DARK_ERROR_CONTAINER),
        onError = Color(GREEN_DARK_ON_ERROR),
        onErrorContainer = Color(GREEN_DARK_ON_ERROR_CONTAINER),
        background = Color(GREEN_DARK_BACKGROUND),
        onBackground = Color(GREEN_DARK_ON_BACKGROUND),
        surface = Color(GREEN_DARK_SURFACE),
        onSurface = Color(GREEN_DARK_ON_SURFACE),
        surfaceVariant = Color(GREEN_DARK_SURFACE_VARIANT),
        onSurfaceVariant = Color(GREEN_DARK_ON_SURFACE_VARIANT),
        outline = Color(GREEN_DARK_OUTLINE),
        inverseOnSurface = Color(GREEN_DARK_INVERSE_ON_SURFACE),
        inverseSurface = Color(GREEN_DARK_INVERSE_SURFACE),
        inversePrimary = Color(GREEN_DARK_INVERSE_PRIMARY),
        surfaceTint = Color(GREEN_DARK_SURFACE_TINT)
    )

    private val pinkLight = lightColorScheme(
        primary = Color(PINK_LIGHT_PRIMARY),
        onPrimary = Color(PINK_LIGHT_ON_PRIMARY),
        primaryContainer = Color(PINK_LIGHT_PRIMARY_CONTAINER),
        onPrimaryContainer = Color(PINK_LIGHT_ON_PRIMARY_CONTAINER),
        secondary = Color(PINK_LIGHT_SECONDARY),
        onSecondary = Color(PINK_LIGHT_ON_SECONDARY),
        secondaryContainer = Color(PINK_LIGHT_SECONDARY_CONTAINER),
        onSecondaryContainer = Color(PINK_LIGHT_ON_SECONDARY_CONTAINER),
        tertiary = Color(PINK_LIGHT_TERTIARY),
        onTertiary = Color(PINK_LIGHT_ON_TERTIARY),
        tertiaryContainer = Color(PINK_LIGHT_TERTIARY_CONTAINER),
        onTertiaryContainer = Color(PINK_LIGHT_ON_TERTIARY_CONTAINER),
        error = Color(PINK_LIGHT_ERROR),
        errorContainer = Color(PINK_LIGHT_ERROR_CONTAINER),
        onError = Color(PINK_LIGHT_ON_ERROR),
        onErrorContainer = Color(PINK_LIGHT_ON_ERROR_CONTAINER),
        background = Color(PINK_LIGHT_BACKGROUND),
        onBackground = Color(PINK_LIGHT_ON_BACKGROUND),
        surface = Color(PINK_LIGHT_SURFACE),
        onSurface = Color(PINK_LIGHT_ON_SURFACE),
        surfaceVariant = Color(PINK_LIGHT_SURFACE_VARIANT),
        onSurfaceVariant = Color(PINK_LIGHT_ON_SURFACE_VARIANT),
        outline = Color(PINK_LIGHT_OUTLINE),
        inverseOnSurface = Color(PINK_LIGHT_INVERSE_ON_SURFACE),
        inverseSurface = Color(PINK_LIGHT_INVERSE_SURFACE),
        inversePrimary = Color(PINK_LIGHT_INVERSE_PRIMARY),
        surfaceTint = Color(PINK_LIGHT_SURFACE_TINT),
    )

    private val pinkDark = darkColorScheme(
        primary = Color(PINK_DARK_PRIMARY),
        onPrimary = Color(PINK_DARK_ON_PRIMARY),
        primaryContainer = Color(PINK_DARK_PRIMARY_CONTAINER),
        onPrimaryContainer = Color(PINK_DARK_ON_PRIMARY_CONTAINER),
        secondary = Color(PINK_DARK_SECONDARY),
        onSecondary = Color(PINK_DARK_ON_SECONDARY),
        secondaryContainer = Color(PINK_DARK_SECONDARY_CONTAINER),
        onSecondaryContainer = Color(PINK_DARK_ON_SECONDARY_CONTAINER),
        tertiary = Color(PINK_DARK_TERTIARY),
        onTertiary = Color(PINK_DARK_ON_TERTIARY),
        tertiaryContainer = Color(PINK_DARK_TERTIARY_CONTAINER),
        onTertiaryContainer = Color(PINK_DARK_ON_TERTIARY_CONTAINER),
        error = Color(PINK_DARK_ERROR),
        errorContainer = Color(PINK_DARK_ERROR_CONTAINER),
        onError = Color(PINK_DARK_ON_ERROR),
        onErrorContainer = Color(PINK_DARK_ON_ERROR_CONTAINER),
        background = Color(PINK_DARK_BACKGROUND),
        onBackground = Color(PINK_DARK_ON_BACKGROUND),
        surface = Color(PINK_DARK_SURFACE),
        onSurface = Color(PINK_DARK_ON_SURFACE),
        surfaceVariant = Color(PINK_DARK_SURFACE_VARIANT),
        onSurfaceVariant = Color(PINK_DARK_ON_SURFACE_VARIANT),
        outline = Color(PINK_DARK_OUTLINE),
        inverseOnSurface = Color(PINK_DARK_INVERSE_ON_SURFACE),
        inverseSurface = Color(PINK_DARK_INVERSE_SURFACE),
        inversePrimary = Color(PINK_DARK_INVERSE_PRIMARY),
        surfaceTint = Color(PINK_DARK_SURFACE_TINT),
    )

    private val yellowLight = lightColorScheme(
        primary = Color(YELLOW_LIGHT_PRIMARY),
        onPrimary = Color(YELLOW_LIGHT_ON_PRIMARY),
        primaryContainer = Color(YELLOW_LIGHT_PRIMARY_CONTAINER),
        onPrimaryContainer = Color(YELLOW_LIGHT_ON_PRIMARY_CONTAINER),
        secondary = Color(YELLOW_LIGHT_SECONDARY),
        onSecondary = Color(YELLOW_LIGHT_ON_SECONDARY),
        secondaryContainer = Color(YELLOW_LIGHT_SECONDARY_CONTAINER),
        onSecondaryContainer = Color(YELLOW_LIGHT_ON_SECONDARY_CONTAINER),
        tertiary = Color(YELLOW_LIGHT_TERTIARY),
        onTertiary = Color(YELLOW_LIGHT_ON_TERTIARY),
        tertiaryContainer = Color(YELLOW_LIGHT_TERTIARY_CONTAINER),
        onTertiaryContainer = Color(YELLOW_LIGHT_ON_TERTIARY_CONTAINER),
        error = Color(YELLOW_LIGHT_ERROR),
        errorContainer = Color(YELLOW_LIGHT_ERROR_CONTAINER),
        onError = Color(YELLOW_LIGHT_ON_ERROR),
        onErrorContainer = Color(YELLOW_LIGHT_ON_ERROR_CONTAINER),
        background = Color(YELLOW_LIGHT_BACKGROUND),
        onBackground = Color(YELLOW_LIGHT_ON_BACKGROUND),
        surface = Color(YELLOW_LIGHT_SURFACE),
        onSurface = Color(YELLOW_LIGHT_ON_SURFACE),
        surfaceVariant = Color(YELLOW_LIGHT_SURFACE_VARIANT),
        onSurfaceVariant = Color(YELLOW_LIGHT_ON_SURFACE_VARIANT),
        outline = Color(YELLOW_LIGHT_OUTLINE),
        inverseOnSurface = Color(YELLOW_LIGHT_INVERSE_ON_SURFACE),
        inverseSurface = Color(YELLOW_LIGHT_INVERSE_SURFACE),
        inversePrimary = Color(YELLOW_LIGHT_INVERSE_PRIMARY),
        surfaceTint = Color(YELLOW_LIGHT_SURFACE_TINT),
    )

    private val yellowDark = darkColorScheme(
        primary = Color(YELLOW_DARK_PRIMARY),
        onPrimary = Color(YELLOW_DARK_ON_PRIMARY),
        primaryContainer = Color(YELLOW_DARK_PRIMARY_CONTAINER),
        onPrimaryContainer = Color(YELLOW_DARK_ON_PRIMARY_CONTAINER),
        secondary = Color(YELLOW_DARK_SECONDARY),
        onSecondary = Color(YELLOW_DARK_ON_SECONDARY),
        secondaryContainer = Color(YELLOW_DARK_SECONDARY_CONTAINER),
        onSecondaryContainer = Color(YELLOW_DARK_ON_SECONDARY_CONTAINER),
        tertiary = Color(YELLOW_DARK_TERTIARY),
        onTertiary = Color(YELLOW_DARK_ON_TERTIARY),
        tertiaryContainer = Color(YELLOW_DARK_TERTIARY_CONTAINER),
        onTertiaryContainer = Color(YELLOW_DARK_ON_TERTIARY_CONTAINER),
        error = Color(YELLOW_DARK_ERROR),
        errorContainer = Color(YELLOW_DARK_ERROR_CONTAINER),
        onError = Color(YELLOW_DARK_ON_ERROR),
        onErrorContainer = Color(YELLOW_DARK_ON_ERROR_CONTAINER),
        background = Color(YELLOW_DARK_BACKGROUND),
        onBackground = Color(YELLOW_DARK_ON_BACKGROUND),
        surface = Color(YELLOW_DARK_SURFACE),
        onSurface = Color(YELLOW_DARK_ON_SURFACE),
        surfaceVariant = Color(YELLOW_DARK_SURFACE_VARIANT),
        onSurfaceVariant = Color(YELLOW_DARK_ON_SURFACE_VARIANT),
        outline = Color(YELLOW_DARK_OUTLINE),
        inverseOnSurface = Color(YELLOW_DARK_INVERSE_ON_SURFACE),
        inverseSurface = Color(YELLOW_DARK_INVERSE_SURFACE),
        inversePrimary = Color(YELLOW_DARK_INVERSE_PRIMARY),
        surfaceTint = Color(YELLOW_DARK_SURFACE_TINT)
    )

    private val lavenderLight = lightColorScheme(
        primary = Color(LAVENDER_LIGHT_PRIMARY),
        onPrimary = Color(LAVENDER_LIGHT_ON_PRIMARY),
        primaryContainer = Color(LAVENDER_LIGHT_PRIMARY_CONTAINER),
        onPrimaryContainer = Color(LAVENDER_LIGHT_ON_PRIMARY_CONTAINER),
        secondary = Color(LAVENDER_LIGHT_SECONDARY),
        onSecondary = Color(LAVENDER_LIGHT_ON_SECONDARY),
        secondaryContainer = Color(LAVENDER_LIGHT_SECONDARY_CONTAINER),
        onSecondaryContainer = Color(LAVENDER_LIGHT_ON_SECONDARY_CONTAINER),
        tertiary = Color(LAVENDER_LIGHT_TERTIARY),
        onTertiary = Color(LAVENDER_LIGHT_ON_TERTIARY),
        tertiaryContainer = Color(LAVENDER_LIGHT_TERTIARY_CONTAINER),
        onTertiaryContainer = Color(LAVENDER_LIGHT_ON_TERTIARY_CONTAINER),
        error = Color(LAVENDER_LIGHT_ERROR),
        errorContainer = Color(LAVENDER_LIGHT_ERROR_CONTAINER),
        onError = Color(LAVENDER_LIGHT_ON_ERROR),
        onErrorContainer = Color(LAVENDER_LIGHT_ON_ERROR_CONTAINER),
        background = Color(LAVENDER_LIGHT_BACKGROUND),
        onBackground = Color(LAVENDER_LIGHT_ON_BACKGROUND),
        surface = Color(LAVENDER_LIGHT_SURFACE),
        onSurface = Color(LAVENDER_LIGHT_ON_SURFACE),
        surfaceVariant = Color(LAVENDER_LIGHT_SURFACE_VARIANT),
        onSurfaceVariant = Color(LAVENDER_LIGHT_ON_SURFACE_VARIANT),
        outline = Color(LAVENDER_LIGHT_OUTLINE),
        inverseOnSurface = Color(LAVENDER_LIGHT_INVERSE_ON_SURFACE),
        inverseSurface = Color(LAVENDER_LIGHT_INVERSE_SURFACE),
        inversePrimary = Color(LAVENDER_LIGHT_INVERSE_PRIMARY),
        surfaceTint = Color(LAVENDER_LIGHT_SURFACE_TINT),
    )

    private val lavenderDark = darkColorScheme(
        primary = Color(LAVENDER_DARK_PRIMARY),
        onPrimary = Color(LAVENDER_DARK_ON_PRIMARY),
        primaryContainer = Color(LAVENDER_DARK_PRIMARY_CONTAINER),
        onPrimaryContainer = Color(LAVENDER_DARK_ON_PRIMARY_CONTAINER),
        secondary = Color(LAVENDER_DARK_SECONDARY),
        onSecondary = Color(LAVENDER_DARK_ON_SECONDARY),
        secondaryContainer = Color(LAVENDER_DARK_SECONDARY_CONTAINER),
        onSecondaryContainer = Color(LAVENDER_DARK_ON_SECONDARY_CONTAINER),
        tertiary = Color(LAVENDER_DARK_TERTIARY),
        onTertiary = Color(LAVENDER_DARK_ON_TERTIARY),
        tertiaryContainer = Color(LAVENDER_DARK_TERTIARY_CONTAINER),
        onTertiaryContainer = Color(LAVENDER_DARK_ON_TERTIARY_CONTAINER),
        error = Color(LAVENDER_DARK_ERROR),
        errorContainer = Color(LAVENDER_DARK_ERROR_CONTAINER),
        onError = Color(LAVENDER_DARK_ON_ERROR),
        onErrorContainer = Color(LAVENDER_DARK_ON_ERROR_CONTAINER),
        background = Color(LAVENDER_DARK_BACKGROUND),
        onBackground = Color(LAVENDER_DARK_ON_BACKGROUND),
        surface = Color(LAVENDER_DARK_SURFACE),
        onSurface = Color(LAVENDER_DARK_ON_SURFACE),
        surfaceVariant = Color(LAVENDER_DARK_SURFACE_VARIANT),
        onSurfaceVariant = Color(LAVENDER_DARK_ON_SURFACE_VARIANT),
        outline = Color(LAVENDER_DARK_OUTLINE),
        inverseOnSurface = Color(LAVENDER_DARK_INVERSE_ON_SURFACE),
        inverseSurface = Color(LAVENDER_DARK_INVERSE_SURFACE),
        inversePrimary = Color(LAVENDER_DARK_INVERSE_PRIMARY),
        surfaceTint = Color(LAVENDER_DARK_SURFACE_TINT),
    )

    private val blackAndWhiteLight = lightColorScheme(
        primary = Color(BLACK_AND_WHITE_LIGHT_PRIMARY),
        onPrimary = Color(BLACK_AND_WHITE_LIGHT_ON_PRIMARY),
        primaryContainer = Color(BLACK_AND_WHITE_LIGHT_PRIMARY_CONTAINER),
        onPrimaryContainer = Color(BLACK_AND_WHITE_LIGHT_ON_PRIMARY_CONTAINER),
        secondary = Color(BLACK_AND_WHITE_LIGHT_SECONDARY),
        onSecondary = Color(BLACK_AND_WHITE_LIGHT_ON_SECONDARY),
        secondaryContainer = Color(BLACK_AND_WHITE_LIGHT_SECONDARY_CONTAINER),
        onSecondaryContainer = Color(BLACK_AND_WHITE_LIGHT_ON_SECONDARY_CONTAINER),
        tertiary = Color(BLACK_AND_WHITE_LIGHT_TERTIARY),
        onTertiary = Color(BLACK_AND_WHITE_LIGHT_ON_TERTIARY),
        tertiaryContainer = Color(BLACK_AND_WHITE_LIGHT_TERTIARY_CONTAINER),
        onTertiaryContainer = Color(BLACK_AND_WHITE_LIGHT_ON_TERTIARY_CONTAINER),
        error = Color(BLACK_AND_WHITE_LIGHT_ERROR),
        errorContainer = Color(BLACK_AND_WHITE_LIGHT_ERROR_CONTAINER),
        onError = Color(BLACK_AND_WHITE_LIGHT_ON_ERROR),
        onErrorContainer = Color(BLACK_AND_WHITE_LIGHT_ON_ERROR_CONTAINER),
        background = Color(BLACK_AND_WHITE_LIGHT_BACKGROUND),
        onBackground = Color(BLACK_AND_WHITE_LIGHT_ON_BACKGROUND),
        surface = Color(BLACK_AND_WHITE_LIGHT_SURFACE),
        onSurface = Color(BLACK_AND_WHITE_LIGHT_ON_SURFACE),
        surfaceVariant = Color(BLACK_AND_WHITE_LIGHT_SURFACE_VARIANT),
        onSurfaceVariant = Color(BLACK_AND_WHITE_LIGHT_ON_SURFACE_VARIANT),
        outline = Color(BLACK_AND_WHITE_LIGHT_OUTLINE),
        inverseOnSurface = Color(BLACK_AND_WHITE_LIGHT_INVERSE_ON_SURFACE),
        inverseSurface = Color(BLACK_AND_WHITE_LIGHT_INVERSE_SURFACE),
        inversePrimary = Color(BLACK_AND_WHITE_LIGHT_INVERSE_PRIMARY),
        surfaceTint = Color(BLACK_AND_WHITE_LIGHT_SURFACE_TINT),
    )

    private val blackAndWhiteDark = darkColorScheme(
        primary = Color(BLACK_AND_WHITE_DARK_PRIMARY),
        onPrimary = Color(BLACK_AND_WHITE_DARK_ON_PRIMARY),
        primaryContainer = Color(BLACK_AND_WHITE_DARK_PRIMARY_CONTAINER),
        onPrimaryContainer = Color(BLACK_AND_WHITE_DARK_ON_PRIMARY_CONTAINER),
        secondary = Color(BLACK_AND_WHITE_DARK_SECONDARY),
        onSecondary = Color(BLACK_AND_WHITE_DARK_ON_SECONDARY),
        secondaryContainer = Color(BLACK_AND_WHITE_DARK_SECONDARY_CONTAINER),
        onSecondaryContainer = Color(BLACK_AND_WHITE_DARK_ON_SECONDARY_CONTAINER),
        tertiary = Color(BLACK_AND_WHITE_DARK_TERTIARY),
        onTertiary = Color(BLACK_AND_WHITE_DARK_ON_TERTIARY),
        tertiaryContainer = Color(BLACK_AND_WHITE_DARK_TERTIARY_CONTAINER),
        onTertiaryContainer = Color(BLACK_AND_WHITE_DARK_ON_TERTIARY_CONTAINER),
        error = Color(BLACK_AND_WHITE_DARK_ERROR),
        errorContainer = Color(BLACK_AND_WHITE_DARK_ERROR_CONTAINER),
        onError = Color(BLACK_AND_WHITE_DARK_ON_ERROR),
        onErrorContainer = Color(BLACK_AND_WHITE_DARK_ON_ERROR_CONTAINER),
        background = Color(BLACK_AND_WHITE_DARK_BACKGROUND),
        onBackground = Color(BLACK_AND_WHITE_DARK_ON_BACKGROUND),
        surface = Color(BLACK_AND_WHITE_DARK_SURFACE),
        onSurface = Color(BLACK_AND_WHITE_DARK_ON_SURFACE),
        surfaceVariant = Color(BLACK_AND_WHITE_DARK_SURFACE_VARIANT),
        onSurfaceVariant = Color(BLACK_AND_WHITE_DARK_ON_SURFACE_VARIANT),
        outline = Color(BLACK_AND_WHITE_DARK_OUTLINE),
        inverseOnSurface = Color(BLACK_AND_WHITE_DARK_INVERSE_ON_SURFACE),
        inverseSurface = Color(BLACK_AND_WHITE_DARK_INVERSE_SURFACE),
        inversePrimary = Color(BLACK_AND_WHITE_DARK_INVERSE_PRIMARY),
        surfaceTint = Color(BLACK_AND_WHITE_DARK_SURFACE_TINT),
    )

    private val blueLight = lightColorScheme(
        primary = Color(BLUE_LIGHT_PRIMARY),
        onPrimary = Color(BLUE_LIGHT_ON_PRIMARY),
        primaryContainer = Color(BLUE_LIGHT_PRIMARY_CONTAINER),
        onPrimaryContainer = Color(BLUE_LIGHT_ON_PRIMARY_CONTAINER),
        secondary = Color(BLUE_LIGHT_SECONDARY),
        onSecondary = Color(BLUE_LIGHT_ON_SECONDARY),
        secondaryContainer = Color(BLUE_LIGHT_SECONDARY_CONTAINER),
        onSecondaryContainer = Color(BLUE_LIGHT_ON_SECONDARY_CONTAINER),
        tertiary = Color(BLUE_LIGHT_TERTIARY),
        onTertiary = Color(BLUE_LIGHT_ON_TERTIARY),
        tertiaryContainer = Color(BLUE_LIGHT_TERTIARY_CONTAINER),
        onTertiaryContainer = Color(BLUE_LIGHT_ON_TERTIARY_CONTAINER),
        error = Color(BLUE_LIGHT_ERROR),
        errorContainer = Color(BLUE_LIGHT_ERROR_CONTAINER),
        onError = Color(BLUE_LIGHT_ON_ERROR),
        onErrorContainer = Color(BLUE_LIGHT_ON_ERROR_CONTAINER),
        background = Color(BLUE_LIGHT_BACKGROUND),
        onBackground = Color(BLUE_LIGHT_ON_BACKGROUND),
        inverseOnSurface = Color(BLUE_LIGHT_INVERSE_ON_SURFACE),
        inverseSurface = Color(BLUE_LIGHT_INVERSE_SURFACE),
        inversePrimary = Color(BLUE_LIGHT_INVERSE_PRIMARY),
        surfaceTint = Color(BLUE_LIGHT_SURFACE_TINT),
        outlineVariant = Color(BLUE_LIGHT_OUTLINE_VARIANT),
        scrim = Color(BLUE_LIGHT_SCRIM),
        surface = Color(BLUE_LIGHT_SURFACE),
        onSurface = Color(BLUE_LIGHT_ON_SURFACE)
    )

    private val blueDark = darkColorScheme(
        primary = Color(BLUE_DARK_PRIMARY),
        onPrimary = Color(BLUE_DARK_ON_PRIMARY),
        primaryContainer = Color(BLUE_DARK_PRIMARY_CONTAINER),
        onPrimaryContainer = Color(BLUE_DARK_ON_PRIMARY_CONTAINER),
        secondary = Color(BLUE_DARK_SECONDARY),
        onSecondary = Color(BLUE_DARK_ON_SECONDARY),
        secondaryContainer = Color(BLUE_DARK_SECONDARY_CONTAINER),
        onSecondaryContainer = Color(BLUE_DARK_ON_SECONDARY_CONTAINER),
        tertiary = Color(BLUE_DARK_TERTIARY),
        onTertiary = Color(BLUE_DARK_ON_TERTIARY),
        tertiaryContainer = Color(BLUE_DARK_TERTIARY_CONTAINER),
        onTertiaryContainer = Color(BLUE_DARK_ON_TERTIARY_CONTAINER),
        error = Color(BLUE_DARK_ERROR),
        errorContainer = Color(BLUE_DARK_ERROR_CONTAINER),
        onError = Color(BLUE_DARK_ON_ERROR),
        onErrorContainer = Color(BLUE_DARK_ON_ERROR_CONTAINER),
        background = Color(BLUE_DARK_BACKGROUND),
        onBackground = Color(BLUE_DARK_ON_BACKGROUND),
        outline = Color(BLUE_DARK_OUTLINE),
        inverseOnSurface = Color(BLUE_DARK_INVERSE_ON_SURFACE),
        inverseSurface = Color(BLUE_DARK_INVERSE_SURFACE),
        inversePrimary = Color(BLUE_DARK_INVERSE_PRIMARY),
        surfaceTint = Color(BLUE_DARK_SURFACE_TINT),
        outlineVariant = Color(BLUE_DARK_OUTLINE_VARIANT),
        scrim = Color(BLUE_DARK_SCRIM),
        surface = Color(BLUE_DARK_SURFACE),
        onSurface = Color(BLUE_DARK_ON_SURFACE),
        surfaceVariant = Color(BLUE_DARK_SURFACE_VARIANT),
        onSurfaceVariant = Color(BLUE_DARK_ON_SURFACE_VARIANT)
    )
}

enum class AppTheme {
    Green,
    Blue,
    Peach,
    Yellow,
    Lavender,
    BlackAndWhite
}
